name: Run Postman Collections and Send Results to Slack

on:
  push:
    branches:
      - main

jobs:
  run_postman_collections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Newman
        run: npm install -g newman@5.2.3

      - name: Run Collection 1 and Generate HTML Report
        run: newman run petarS.postman_collection.json --reporters cli,html
        continue-on-error: true

      - name: Create Newman Report Gist
        run: |
          cat newman/HTMLReport.html > report.html
          gist create -d "Postman Collection 1 Results" report.html
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}

      - name: Get Gist URL
        id: get_gist
        run: |
          echo "::set-output name=gist_url::$(gist ls -a | grep 'Postman Collection 1 Results' | awk '{print $1}')"
        continue-on-error: true

      - name: Send Results to Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          text: "Postman Collection 1 Results: ${{ steps.get_gist.outputs.gist_url }}"
          author_name: "GitHub Actions"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
