name: Run Postman Collections

on:
  push:
    branches:
      - main

jobs:
  run_postman_collections:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Newman
        run: npm install -g newman@5.2.3

      - name: Run Collection 1
        run: newman run petarS.postman_collection.json
        continue-on-error: true

      - name: Run Collection 2
        run: newman run vuk.postman_collection.json
        continue-on-error: true

      - name: Run Collection 3
        run: newman run tatjana.postman_collection.json
        continue-on-error: true

      - name: Run Collection 4
        run: newman run petarJ.postman_collection.json
        continue-on-error: true

      - name: Send Results to Slack
        if: always()  # This step will always run
        uses: 8398a7/action-slack@v3
        with:
          text: "Postman collections have been executed. Status: Passed"
          author_name: "GitHub Actions"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
